apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: mongoose-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:fade073733105ad2f9e4b47c0a90dfdc3d6dab07@sha256:234742a8afc4eabbe6fd1ccd200763110d38c8bd1e65f6d28d82d5205004fa4f
        name: container-image  
